### PR TITLE
Publish mode

### PR DESCRIPTION
**Pull request by btzr-io**
Identify how the user is publishing the content:
- Input file ( local file system )
- Drag-drop file ( local file system ) https://github.com/lbryio/lbry-desktop/issues/350
- In-app text / markdown generated file ( web fileSystem API ) https://github.com/lbryio/lbry-desktop/issues/4105
- Others ?....

```js
// OnFileDrop:
updatePublishForm({ filePath: string || webFile, mode: PUBLISH_MODE.DROP } });

// Select file on fileSelector:
// OnFileChange:
updatePublishForm({ filePath: string || webFile, mode: PUBLISH_MODE.INPUT } });

// Post creation
const post = createFile().write("text from user input");
updatePublishForm({ filePath: post, mode: PUBLISH_MODE.POST } });
```

### Todo
- [ ]  Constant types for publish modes

### CODE REVIEW

**Comment by btzr-io** [comment]
I think this approach is really simple, not sure if is the best to handle new features / forms of publishing ?

**Comment by seanyesmunt** [comment]
Does the UI change in "drop" mode? Or does that just make it so dropping a file works?

**Comment by btzr-io** [comment]
Nope it does not change the UI, I think I can make it work without this but I'll need to rewrite more code...

Publish mode will probably change the UI, but I don't know yet how exactly will it work.

**Comment by seanyesmunt** [comment]
👍 If it's not changing the UI I don't think it will need it's own mode?

**Pull request closed without merging**
