### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**

### CODE REVIEW

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Comment by sakshamtaneja21** [comment]
https://www.jabref.org/hacktoberfest/2019.html regarding this how can i get tshirt

**Comment by sakshamtaneja21** [comment]
lbry.com/news/hacktoberfest-2019  when will I receive this

**Comment by tzarebczan** [comment]
Sorry, only actual code changes qualify and you spammed our other repos.

**Pull request merged**
