### PR TITLE
Add release time to publish

### PR DESCRIPTION
**Pull request by Ruk33**
Required by 

Issue: https://github.com/lbryio/lbry-desktop/issues/2328
PR: https://github.com/lbryio/lbry-desktop/pull/5514

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Please run `yarn build` to build this in production mode

**Comment by Ruk33** [comment]
Hi @seanyesmunt , done. It may be a good idea to add a pre-commit hook to run `yarn build`. What do you think? Regards.

**Comment by Ruk33** [comment]
Hello @seanyesmunt , is this ok? Please let me know if I need to do anything else. Thanks!

**Comment by seanyesmunt** [comment]
@Ruk33 Yes this looks good. Was just waiting to test with the desktop PR (doing that now)

**Pull request merged**
